apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hew5ubpin-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hew5ubpin-python 
  name: hew5ubpin-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hew5ubpin-python 
